JNG-4473 Release judo jsl springboot parent
BlackBeltTechnology/judo-jsl-springboot-parent pull request #40
Opened 2023-02-22 16:42 UTC by gaborflorian

2023-02-22 17:11 UTC, bencegelei approved these changes

2023-02-22 19:18 UTC, robertcsakany requested changes

2023-02-22 19:18 UTC, robertcsakany commented on .github/workflows/build-dependabot.yml
> +          echo "VERSION=${VERSION_NUMBER}" >> $GITHUB_OUTPUT
Please use lower case name

2023-02-23 10:59 UTC, gaborflorian commented on .github/workflows/build-dependabot.yml
> +          echo "VERSION=${VERSION_NUMBER}" >> $GITHUB_OUTPUT
[d3018fd](https://github.com/BlackBeltTechnology/judo-jsl-springboot-parent/pull/40/commits/d3018fd6bdfc85e57430c7be223e3cafaffb11f0)

2023-02-23 14:45 UTC, robertcsakany approved these changes

2023-02-24 08:29 UTC, fmagnucz approved these changes

2023-02-28 15:05 UTC, merged